# By PuXiongfei

name: Build Armbian

on:
  workflow_dispatch:
    inputs:
      boards:
        description: "BOARD"
        required: true
        default: "phicomm-n1"
      branch:
        description: "BRANCH"
        required: true
        default: "edge"
      release:
        description: "RELEASE"
        required: true
        default: "bullseye"
      buildMinimal:
        description: "BUILD_MINIMAL"
        required: true
        default: "no"
      buildDesktop:
        description: "BUILD_DESKTOP"
        required: true
        default: "no"
      override:
        description: "override files"
        required: true
        default: "yes"
      exclude:
        description: "exclude files"
        required: false

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10240
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"

      - name: Initialization environment
        run: |
          echo "Free space:"
          df -hT
          sudo timedatectl set-timezone "$TZ"

      - name: Checkout self
        uses: actions/checkout@v2

      - name: Checkout Armbian build script
        uses: actions/checkout@v2
        with:
          path: build
          repository: armbian/build
          ref: master

      - name: Override file
        run: |
          echo "$(date +"%Y.%m.%d")-PuXiongfei" > build/VERSION
          if [[ "${{ github.event.inputs.override }}" == "yes" && -d override ]]; then
            BIN_PATH=$(curl -s https://api.github.com/repos/PuXiongfei/phicomm-n1-u-boot/releases/latest | grep browser_download_url | cut -d '"' -f 4)
            wget -O override/userpatches/phicomm-n1/u-boot.bin ${BIN_PATH}
            mkdir -p override/userpatches/u-boot/u-boot-meson64
            wget -O override/userpatches/u-boot/u-boot-meson64/zzz-phicomm-n1-u-boot.patch https://raw.githubusercontent.com/PuXiongfei/phicomm-n1-u-boot/main/patch/phicomm-n1-u-boot.patch
            echo "Copy override files..."
            cp -af override/* build/
          fi
          if [[ -n "${{ github.event.inputs.exclude }}" ]]; then
            for file in $(echo ${{ github.event.inputs.exclude }} | sed 's/,/ /g')
            do
              echo "find exclude file: $file"
              filePath=$(find build/ -name "$file")
              if [[ -n "$filePath" ]]; then
                echo "delete file: $filePath"
                rm -rf $filePath;
              fi
            done
          fi
          echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: Compile Armbian
        id: compile
        run: |
          cd build
          COMPILE_PARAMS="BOARD=\"${{ github.event.inputs.boards }}\" \
          BRANCH=\"${{ github.event.inputs.branch }}\" \
          RELEASE=\"${{ github.event.inputs.release }}\" \
          KERNEL_ONLY=\"no\" \
          KERNEL_CONFIGURE=\"no\" \
          BUILD_MINIMAL=\"${{ github.event.inputs.buildMinimal }}\" \
          BUILD_DESKTOP=\"${{ github.event.inputs.buildDesktop }}\" \
          EXTERNAL=\"no\" \
          EXPERT=\"yes\" \
          COMPRESS_OUTPUTIMAGE=\"yes\" \
          REGIONAL_MIRROR=\"china\" \
          EXTRAWIFI=\"no\" \
          WIREGUARD=\"no\" \
          DEST_LANG=\"zh_CN.UTF-8\""
          TZDATA=\"Asia/Shanghai\""
          echo "compile params: ${COMPILE_PARAMS}"
          sudo ./compile.sh ${COMPILE_PARAMS}
          echo "::set-output name=status::success"

      - name: Organize files
        id: organize
        if: ${{ steps.compile.outputs.status == 'success' && !cancelled() }}
        run: |
          mkdir -p ${FILE_DATE}
          cd ${FILE_DATE}
          echo "UPLOAD_PATH=${PWD}" >> $GITHUB_ENV
          [[ -d ${GITHUB_WORKSPACE}/build/output ]] && sudo mv -f ${GITHUB_WORKSPACE}/build/output ./
          echo "::set-output name=status::success"

      - name: Upload output
        uses: actions/upload-artifact@v2
        if: ${{ steps.organize.outputs.status == 'success' && !cancelled() }}
        with:
          name: Armbian_${{ github.event.inputs.boards }}_${{ github.event.inputs.release }}_${{ env.FILE_DATE }}
          path: ${{ env.UPLOAD_PATH }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 1
